version: 0.{build}-{branch}

image:
    - Visual Studio 2017

environment:
  global:
    QTVER: 5.11
    JOMDIR: C:\Qt\Tools\QtCreator\bin
    MINGWDIR: C:\Qt\Tools\mingw530_32
    VSVER: 0

  matrix:
    - QTABI: mingw53_32
      ARCH: x86
      MAKETOOL: mingw32-make
      CMAKE_GENERATOR: "MinGW Makefiles"
      USE_CMAKE: true
      MSBUILD_FLAGS: 
#    - QTABI: mingw53_32
#      ARCH: x86
#      QMAKESPEC: win32-g++
#      MAKETOOL: mingw32-make
#      USE_CMAKE: false
    - QTABI: msvc2017_64
      ARCH: x64
      VSVER: 2017
      CMAKE_GENERATOR: "Visual Studio 15 2017 Win64"
      USE_CMAKE: true
      MSBUILD_FLAGS: /verbosity:minimal /maxcpucount
#    - QTABI: msvc2017_64
#      ARCH: x64
#      VSVER: 2017
#      QMAKESPEC: win32-msvc
#      MAKETOOL: jom
#      USE_CMAKE: false
    - QTABI: msvc2015
      ARCH: x86
      VSVER: 14
      CMAKE_GENERATOR: "Visual Studio 15 2017"
      USE_CMAKE: true
      MSBUILD_FLAGS: /verbosity:minimal /maxcpucount
#    - QTABI: msvc2015
#      ARCH: x86
#      VSVER: 14
#      QMAKESPEC: win32-msvc
#      MAKETOOL: jom
#      USE_CMAKE: false

skip_tags: true

build:
  parallel: true
  verbosity: detailed

configuration:
  - release
#  - debug


install:
  - IF %VSVER% GTR 14 (
        call "C:\Program Files (x86)\Microsoft Visual Studio\%VSVER%\Community\VC\Auxiliary\Build\vcvarsall.bat" %ARCH%
    ) ELSE (
        IF %VSVER% GTR 0 (
            call "C:\Program Files (x86)\Microsoft Visual Studio "%VSVER%".0\VC\vcvarsall.bat" %ARCH%
        ) ELSE (
            set "PATH=%MINGWDIR%\bin;%PATH%"
        )
    )
  - set PATH=C:\Qt\%QTVER%\%QTABI%\bin;%JOMDIR%;%PATH%
  - echo "BUILD ID Qt%QTVER%_%QTABI%_%APPVEYOR_BUILD_VERSION%_%CONFIGURATION%"
  # Rename sh.exe as sh.exe in PATH interferes with MinGW
  - rename "C:\Program Files\Git\usr\bin\sh.exe" "sh2.exe"
  - cmd: choco install OpenCV
  - cmd: set OPENCV_DIR=C:\tools\opencv\build

build_script:
#  - dir "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\include"
#  - type "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\include\random"
#  - dir "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE"
#  - type "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE\random"
  - mkdir build
  - cd build
  - if "%CONFIGURATION%"=="release" (set CMAKE_CONFIGURATION=Release) else (set CMAKE_CONFIGURATION=Debug)
  - if [%USE_CMAKE%]==[true] (
      echo "Call CMake..."
      cmake --version &&
      cmake -G "%CMAKE_GENERATOR%" "-DCMAKE_PREFIX_PATH=%QT5%" .. &&
      echo "Build..." &&
      cmake --build . --config "%CMAKE_CONFIGURATION%" -- %MSBUILD_FLAGS% ) 
    else (
      echo "Call QMake..." &&
      qmake.exe -v &&
      qmake.exe CONFIG+=%CONFIGURATION% ..\JKQtPlotterBuildAllExamples.pro &&
      echo "Build..." &&
      call %MAKETOOL% &&
      cd ..)

#artifacts:
#   - path: build\staticlib\**\*.a
#     name: staticlib %QTVER%%QTABI%
#   - path: build\sharedlib\**\*.a
#     name: sharedlib %QTVER%%QTABI%
#   - path: build\staticlib\**\*.lib
#     name: staticlib %QTVER%%QTABI%
#   - path: build\sharedlib\**\*.lib
#     name: sharedlib %QTVER%%QTABI%
#   - path: build\sharedlib\**\*.dll
#     name: dll %QTVER%%QTABI%



# # remote desktop connection on init
# init:
  # - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

# # remote desktop connection on finish and block build to not destroy VM
# on_finish:
  # - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
